name: GriefPreventionTP
version: '${version}'
main: dev.badbird.griefpreventiontp.GriefPreventionTP
author: 'Badbird5907'
website: 'https://badbird.dev'
api-version: 1.13
libraries:
  - com.h2database:h2:2.1.214
depend:
  - GriefPrevention
softdepend:
  - Vault
permissions:
  gptp.reload:
    description: Permission for /gptp reload
  gptp.staff:
    description: Staff permissions
  gptp.command.claims:
    description: Permission for /claims
  gptp.command.claimtp:
    description: Permission for /claimtp
  gptp.command.public:
    description: Permission for /public and /private
  gptp.command.rename:
    description: Permission for /rename
  gptp.command.setspawn:
    description: Permission for /setspawn
  gptp.bypass.public:
    description: Permission for bypassing public claim limit

