name: GriefPreventionTP
version: '${version}'
main: dev.badbird.griefpreventiontp.GriefPreventionTP
author: 'Badbird5907'
website: 'https://badbird.dev'
api-version: 1.13
depend:
  - GriefPrevention
permissions:
  gptp.reload:
    description: Permission for /gptp reload
